apiVersion: v1 
kind: Service
metadata:
  name: clb-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: simple-nginx-app
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# deployment launched: kubernetes_operations/deployment_initContainers.yaml 