apiVersion: v1 
kind: Service
metadata:
  name: nlb-ngix-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # Here we set the lb type
spec:
  type: LoadBalancer
  selector:
    app: simple-nginx-app
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80