apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-go-web-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /hello
spec:
  type: NodePort
  selector:
    app: my-pod-go-app
  ports:
    - name: http 
      port: 8085
      targetPort: 8085