apiVersion: v1
kind: Secret
metadata:
  name: pg-secrets
type: Opaque
data:
  db-password: aG9sYW11bmRvCg== # base64 <<< 'string' to encode /  base64 -d <<< 'base64encoded' to decode 
  db-user: bXlfdXNlcgo=