FROM ubuntu

RUN apt-get update && apt-get install -y apache2 nginx

ADD ./apache.sh /usr/local/bin
ADD ./nginx.sh /usr/local/bin

RUN chmod +x /usr/local/bin/apache.sh && sleep 1 && chmod +x /usr/local/bin/nginx.sh

CMD ["echo ", "Test para lanzar comandos"]

EXPOSE 80