--- 
- name: Create users with loop
  hosts: mysql
  vars_files: ./usuarios_vars.yaml
  tasks:
  - name: Create users
    become: true
    become_user: root
    ansible.builtin.user:
      name: "{{item}}"
      state: present
    loop: "{{users_list}}"