apiVersion: v1
kind: Pod #Objeto que creamos
metadata:
  name: pod-nginx-yml # Nombre recurso 
  namespace: default # Namespace donde alojar el recurso
  labels:
    # labels Permite poner etiquetas a los recursos
    zone: desarrollo
    version: "1.0.1" # Version de la app
    app: "test-1"
  annotations:
    description: "Pod que ejecuta un contenedor nginx con página de ejemplo"
    maintainer: "italianodev"
spec:
  containers:
  # Containers del pod 1 o mas 
  - name: ctn-nginx # nombre contenedor 
    image: italianodev/img-nginx-kubernets:1.0.0 # Imagen
    ports:
    - containerPort: 80 # Puerto expuesto por el contenedor
