apiVersion: v1
kind: Pod

metadata:
  name: k0s-web2
  labels:
    maintainer: italianodevops
    app: k0s-web2

spec:
  containers:
    - name: front2 
      image: nginx:latest
      ports:
        - containerPort: 80