apiVersion: v1
kind: Service
metadata: #Labels to identify resource
  name: nginx-service
  labels:
    maintainer: italianodevops
    app: my-nginx
    tier: frontend
    env: development
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30518
  selector: # Find specific resource identified by labels defined into the metadata section
    app: my-nginx
    env: development

---

apiVersion: apps/v1
kind: ReplicaSet
metadata: #Labels to identify resource
  name: nginx-replicaset-1
  labels:
    maintainer: italianodevops
    app: my-nginx
    tier: frontend
    env: development
spec:
  replicas: 3
  selector: # Find specific resource identified by labels defined into the metadata section
    matchLabels:
      app: my-nginx
      env: development
  template:  # Pods info
    metadata:
      labels:
        maintainer: italianodevops
        app: my-nginx
        tier: frontend
        env: development
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
