FROM mysql:lts

LABEL developer="elitalianodev" version="1.0.0" description="Backend for gospy"

COPY ./initbbdd.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

#docker build -t nombre-imagen:version ./contexto/dockerfile
#docker run -d --env-file=mi-archivo -p 3306:3306 imagen:version