#Selectors -> Objeto primario con los que se relacionan algunos componentes: Deployment, replica-sets,servicios etc...
#Son como "where" en sql se utilizan para seleccionar, localizar objetos con determinada etiquetas
apiVersion: "v1"
kind: Pod
metadata:
  name: t2
  labels:
    entorno: "integracion"
    manteiner: "torvall"
spec:
  containers:
  - name: t2-ctn
    image: tomcat
